### ISSUE TITLE
Problem with umlauts in #hashtags

### ISSUE THREAD

**Issue by pep-** [ozh/ozh-tweet-archiver#10]
When a twitter hashtag contains a non-ASCII character (like an umlaut, e.g. äüö, or ß), the tweet links to an invalid slug instead of the created tag. 

For example, in https://twitter.mundschenk.at/2015/02/03/pomeranzen-schoenbrunn-thincutnicht-im-bild-die-ueberkochende-marmelade-die-sich-ueber-meinen-herd-verteilt-pic-twitter-comgutzulk6bl/ there is a hashtag "#schönbrunn". Slugs should only contain ASCII characters and on my site, with the Permalauts plugin, they do. So the URL of the created tag is https://twitter.mundschenk.at/tag/schoenbrunn/, but in the tweet the hashtag is linked to https://twitter.mundschenk.at/tag/schönbrunn/ (which does not exist).

**Comment by ozh** [comment]
Seems like a conflict with your "permalauts" plugin (which says on its homepage "Deprecated since WordPress 3.6! Do not use", by the way)

**Comment by pep-** [comment]
With all due respect, I think you are wrong here. The problem is the same with the Permalauts plugin (which is obsolete, but since the notice wasn't pushed to the WP plugin repository, I didn't know). 

I've deleted the plugin and generated a new test tweet for you, with the same effect: Your plugin links to a wrong slug.

https://twitter.mundschenk.at/2015/02/04/emaryllis-nur-ein-kurzer-testtweet-sorry-aeoeue/

**Comment by ozh** [comment]
what are the tags created for this post? Neither https://twitter.mundschenk.at/tag/äöü/ nor https://twitter.mundschenk.at/tag/aou/ work

**Comment by pep-** [comment]
https://twitter.mundschenk.at/tag/aeoeue/

WP (core since 3.6, plugins before that) maps Ä/ä to ae, Ö/ö to oe, Ü/ü to ue, ß to ss if the locale is set to de_DE. There are some additional rules for da_DK, as well (all in /wp-includes/formatting.php).
