### ISSUE TITLE
Is it possible to add an option to pre-format posts?

### ISSUE THREAD

**Issue by dinchamion** [ozh/ozh-tweet-archiver#12]
I'm wondering - when the plugin pulls in retweets, would it be possible to insert a new line before the tweet link, so WP can automatically embed the tweet?

Currently it looks like this:
![screen shot 2015-06-14 at 02 05 37](https://cloud.githubusercontent.com/assets/7282347/8146750/1a807580-123a-11e5-919c-cc7922f02efa.png)

And it'd be great if we could automatically format it so it appears as this:
![screen shot 2015-06-14 at 02 07 05](https://cloud.githubusercontent.com/assets/7282347/8146752/29a4ac52-123a-11e5-8092-7b66b4864bb6.png)

I've been trying to dig into the code, but so far no luck in identifying what exactly would need changing. Even a quick hack pointing me in the right direction would be appreciated. :-)

**Comment by ozh** [comment]
Nice idea, should be fixed with this commit

**Comment by dinchamion** [comment]
Works like a charm! :-) Thank you!
