### ISSUE TITLE
Only first attached image appears

### ISSUE THREAD

**Issue by kw217** [ozh/ozh-tweet-archiver#23]
A Twitter image link can contain up to four (I think) images. ozh-tweet-archiver only shows the first one. Is there a way to enable display of multiple images? Or can you point me at where in the code this could be fixed?

Example:
* ozh: http://gurunoia.lochan.org/tweets/2015/11/13/its-been-a-while-since-the-last-polmont-platform-extension-update-as-you-can-see-its-getting-close-to-finished-pic-twitter-comj1jwx8cscb/
* Twitter: https://twitter.com/kw217/statuses/665084868737507328

Thanks.

--KW 8-)

**Comment by ozh** [comment]
Indeed. Patch welcome ! :)
