### ISSUE TITLE
Tweet Limit?

### ISSUE THREAD

**Issue by chrisaldrich** [ozh/ozh-tweet-archiver#26]
I just put together a fresh install and ran the import, but it maxed out at 3200 tweets, which only gets me back to early 2013 rather than my total of 5k+ tweets going back to early 2008. Does Twitter have a hard limit for pulling in tweets historically or is this a bug in the plugin? Or even a daily rate limit?

I know Twitter has a download of one's entire history. Could this data store be used to improve initial import while still maintaining completeness?

This is a great concept and fits right in with the IndieWebCamp.com philosophy. I suspect many in the community there would use this.

**Comment by ozh** [comment]
As explained in the plugin doc on the plugin page.
