### ISSUE TITLE
Truncated tweet content

### ISSUE THREAD

**Issue by spigotdesign** [ozh/ozh-tweet-archiver#28]
Hi Ozh,

I know this is an old app now but I still use (and love) it. I noticed recently that tweet texts are getting truncated. Is this coming from the plugin or is it a limitation from Twitter? Here's an example:

https://spigotdesign.com/tweets/a-recent-woocommerce-stripe-checkout-update-took-us-a-little-by-surprise-gone-was-the-easy-modal-window-process-h-https-twitter-com-i-web-status-1005203118601060352/

vs.

https://twitter.com/spigot/statuses/1005203118601060352

**Comment by ozh** [comment]
Did you update the plugin manually? I don't think I updated the zip on wordpress (havent reinstalled SVN for years...) but latest commit on this git repo adds 280 char support, I think this should fix

**Comment by spigotdesign** [comment]
Thank you sir ;)
