### ISSUE TITLE
Feature request: Import images 

### ISSUE THREAD

**Issue by spigotdesign** [ozh/ozh-tweet-archiver#8]
Currently the plugin displays images hosted on twitter servers. I'd love to be able to self host them.

Is this something you might consider?

**Comment by danielfaulknor** [comment]
@spigotdesign did you get anywhere with this? I was thinking about doing this too

**Comment by spigotdesign** [comment]
@danielfaulknor I ended up using this plugin: https://wordpress.org/plugins/import-external-images/ and periodically run a manual import. I've thought about integrating it but haven't had the time.
