### ISSUE TITLE
Problem when title contains apostrophe

### ISSUE THREAD

**Issue by xavivars** [ozh/ozh-tweet-archiver#9]
I've found a corner case with this plugin, when used combined with SimpleFacebookConnect.

When the editor opens (i.e. www.example.com/wp-admin/post.php?post=123), SimpleFacebookConnect does a filter to the_content to find media.

The problem comes that this filter triggers ozh_ta_convert_old_posts to be executed, with undesired when certain conditions are met (like an apostrophe in the title, being converted to &#36;, detected then by ozh_ta as a hashtag).

Wouldn't be better to trigger ozh_ta_convert_old only on post save instead of on any filter done to the content?

Maybe using the filter in [content_save_pre](http://codex.wordpress.org/Plugin_API/Filter_Reference/content_save_pre) instead of  filtering [the_content](http://codex.wordpress.org/Plugin_API/Filter_Reference/the_content) works better

**Comment by xavivars** [comment]
Maybe using the filter in [content_save_pre](http://codex.wordpress.org/Plugin_API/Filter_Reference/content_save_pre) instead of  filtering [the_content](http://codex.wordpress.org/Plugin_API/Filter_Reference/the_content) works better

**Comment by ozh** [comment]
ozh_ta_convert_old_posts is designed to update post, on the fly when/if they are displayed, from older version of the plugin to current version. Using a pre- hook would not work.

Also, this plugin is designed to manage a tweet archive, nothing else: using other plugins or launching the editor may cause unwanted side effects

In your case, if you didn't use a previous older version of the plugin, I would suggest simply removing the hook to ozh_ta_convert_old_posts

**Comment by xavivars** [comment]
Oh, I have my tweet archive integrated in my blog (that's why other plugins + editing is needed). I've had it like that for some years, without problems.

Only tweak I did was to add a filter to ozh_ta_insert_tweets_post so they are inserted as another post type (called _tweet_) so tweets and posts were not merged.

But I'll remove the hook.

Thanks a lot!
